### ISSUE TITLE
Cannot post tweet when a new address claimed 0.2 LIKE from faucet

### ISSUE THREAD

**Issue by 0xtaipoian** [depub-team/depub.space#107]
Some users reported cannot post a tweet when they used a new create account.

## Steps to reproduce the issue:
1. create a new account
2. claim 0.2 LIKE from faucet
3. post a tweet

**Comment by RicardDeLa** [comment]
I can simulate the issue, showing error "No valid signer, please connect wallet"

It can be reproduce if post tweet  immediately after land to the page

**Comment by RicardDeLa** [comment]
@0xtaipoian  cannot simulate the case 

I tried 
1. create a new account with like1 address, 
2. claim faucet
3. post 3 tweet. all success (2nd tweet use high gas)

Do the user still have problem on posting tweet?
