### ISSUE TITLE
Not showing "nickname" after launching Omniflix option

### ISSUE THREAD

**Issue by susanna2047** [depub-team/depub.space#120]
I got some problem with showing the nickname after depub.space launched the Omniflix option. I found my another account (like1cvpk3j4q5k4tjvfm2cw8dltl5s8fcxvkf6nzpa)  nickname (Jonathan) disappeared which I used Forbole X to create. Even I disconnect the LikeCoin chain and connect again, the nickname is still not shown. I don't know if this problem relates to Forbole x / desmos. After choosing Omniflix to show a NFT as icon, the nickname is also not shown. May I set it in Omniflix? But I can't find the function anyway. Appreciate if you guys can help. Thanks.

**Comment by 0xtaipoian** [comment]
Hi @susanna2047 thanks for reported, we are fixing it now!
