### ISSUE TITLE
Thumbnail not properly shown

### ISSUE THREAD

**Issue by susanna2047** [depub-team/depub.space#132]
Some MingPao (明報) link's preview thumbnail cannot properly shown which is normal before, such as:

https://depub.space/uADG1FkJ0yB58QWzwPW474gcGn6kNURnkJfuUG-C_II/1
https://depub.space/XL5LkXo2A-t-IiTjvDjiDialDYDTTMgod8oKkp0y0dg/1
https://depub.space/FL_GyVgwH8cSFbpdMz3Ex16FWup0neZNYyr87hilsQI/1

The Reporters (報導者) also has the same problem:
https://depub.space/wpLAyr0AysZQwM1fVn4JL1A29Ma1nkhlA7RU5GsyGZQ/1

And also Inmedia (獨立媒體)：
https://depub.space/sRTO2k3klz2BS9NfQzpFLuUnrD-3b16x5UNzOX65hKg/1

Thanks.

**Comment by 0xtaipoian** [comment]
I see first 3 tweets are showing Ming Pao logo, is it correct?

https://www.twreporter.org/a/shinzo-abe-dies-after-being-shot-in-japan not able to get the OG image even open it with https://www.opengraph.xyz/url/https%3A%2F%2Fwww.twreporter.org%2Fa%2Fshinzo-abe-dies-after-being-shot-in-japan

https://bit.ly/3P4Jyf2 bit.ly link doesn't supports OG show also not able to get preview image
https://www.opengraph.xyz/url/https%3A%2F%2Fbit.ly%2F3P4Jyf2

**Comment by 0xtaipoian** [comment]
Close this issue, coz nothing can do for those site doesn't support open graph
