### ISSUE TITLE
Hide URL from tweet if it's shown as OG (image, title, description) already

### ISSUE THREAD

**Issue by mikasa3dom** [depub-team/depub.space#133]
Assuming the logic is to show the first (and only the first) URL of a tweet as OG, suggest to hide the URL without showing it. So the behavior is similar to that of Facebook.

With the integration of Super Like from Liker Land, a lot of the tweets are having only URL and the URLs are very long since they are in Chinese. It's both not looking good, and useless.

**Comment by 0xtaipoian** [comment]
Ok! working on it

**Comment by 0xtaipoian** [comment]
Fixed, remove the url in content
