### ISSUE TITLE
Connect with Cosmostation error after LikeCoin natively included

### ISSUE THREAD

**Issue by mikasa3dom** [depub-team/depub.space#143]
It's been working but after LikeCoin was included natively in Cosmostation, it throws error.

![Screenshot 2022-09-19 at 1 05 36 PM](https://user-images.githubusercontent.com/104421196/191108858-77ffa710-719d-4dbf-aa39-a870e881a084.png)

**Comment by 0xtaipoian** [comment]
Fixed please test
