### ISSUE TITLE
Unique URL for each tweet

### ISSUE THREAD

**Issue by dappledaily** [depub-team/depub.space#54]
e.g. my tweet:
iscn://likecoin-chain/hQyOHtqgMbnJIWw_7Sq8I613fTzOXKGw-cVQjW8G6DI/1

would have a URL of
https://depub.space/depubspace/hQyOHtqgMbnJIWw_7Sq8I613fTzOXKGw-cVQjW8G6DI/1

And if it's updated once:
https://depub.space/depubspace/hQyOHtqgMbnJIWw_7Sq8I613fTzOXKGw-cVQjW8G6DI/2

**Comment by dappledaily** [comment]
Clicking on the tweet in the feed page will bring users to this page (tweet single view)

**Comment by dappledaily** [comment]
- Add [iscn://likecoin-chain/hQyOHtqgMbnJIWw_7Sq8I613fTzOXKGw-cVQjW8G6DI/1](https://app.like.co/view/iscn:%2F%2Flikecoin-chain%2FhQyOHtqgMbnJIWw_7Sq8I613fTzOXKGw-cVQjW8G6DI%2F1) in the unique URL page 
- Add Arweave hash and link to chain data, when applicable

**Comment by 0xtaipoian** [comment]
@dappledaily Arweave hash for image would automatically add into fingerprint, but putting the link into chain data it would be egg and chicken situation, since the link comprised of iscn id, we cannot obtain the iscn id before create the transaction.

**Comment by dappledaily** [comment]
There's a misunderstanding. 

I did NOT mean putting "Arweave hash and link" to chain data.

I meant putting "Arweave hash" and "link to chain data" (ISCN) to the page.

**Comment by dappledaily** [comment]
![Screenshot 2022-03-02 at 9 05 32 PM](https://user-images.githubusercontent.com/86090527/156367522-620a009b-b088-4676-9078-5f35efa4fa50.png)
- Remove ISCN badge in feed view.
- Remove link button in feed view.
- Time ("10 minute ago") clickable and also goes to single tweet view, same as Share button.

![Screenshot 2022-03-02 at 9 07 20 PM](https://user-images.githubusercontent.com/86090527/156367564-163cfd66-0230-4907-a86c-39da77d37843.png)
- When the tweet includes an images, also shows a clickable Arweave hash link below the image.

**Comment by dappledaily** [comment]
Can include this issue in update? Guess easy.

Somehow this issue was closed without being implemented.
