### ISSUE TITLE
#hashtag as "TV channel"

### ISSUE THREAD

**Issue by dappledaily** [depub-team/depub.space#72]
- On left (or right side), show a column of #hashtag, like TV channels, so that users can browse and editor can curate.
- First version:
#standwithukraine
#depub
#likecoin
#[algo hot topics]
[world feed]
- Let users star a channel, which will move to a "Starred" section at the top of the list. Can just stored locally on browser. Can implement in phase2.
- Let editor update channels, say by submitting a JSON as PR. Can implement in phase2.

**Comment by dappledaily** [comment]
"Genesis channels"
#StandWithUkraine
#LikeCoinAirdrop
#depub
#airdrop
#cosmos
#osmosis
#juno

**Comment by 0xtaipoian** [comment]
Fixed

**Comment by 0xtaipoian** [comment]
- [x] Case-insensitive
- [ ] Star a channel
- [ ] Submit channel list as PR

**Comment by 0xtaipoian** [comment]
Channel management has been working via Notion
