### ISSUE TITLE
Let's keep the path /hashtag/ instead of /channel/

### ISSUE THREAD

**Issue by dappledaily** [depub-team/depub.space#77]
Titled. On stag.

**Comment by 0xtaipoian** [comment]
Done

**Comment by dappledaily** [comment]
It's not done.

**Comment by dappledaily** [comment]
Post -> /:iscnid
Hashtag -> /hashtag/:tagname
User -> /user/:handle

**Comment by 0xtaipoian** [comment]
Got it through:
Post -> /:iscnid/:rev
Hashtag -> /hashtag/:tagname
User -> /user/:handle

**Comment by dappledaily** [comment]
The URL copied from "Copy URL" has /post/, which makes it 404.
