### ISSUE TITLE
Hyphenated hashtag seems to be bugged

### ISSUE THREAD

**Issue by dappledaily** [depub-team/depub.space#78]
In:
https://depub.space/post/jtbM3e4CqoZ6LQ8pEL3efXM54NbiGJN5kgFuoZyP0Gc/1

The hashtag #micro-film is empty:
https://depub.space/channel/micro-film

While #production works:
https://depub.space/channel/production

**Comment by 0xtaipoian** [comment]
fixed https://depub.space/channel/likecoin-airdrop
