### ISSUE TITLE
URL from "Copy URL" button wrong

### ISSUE THREAD

**Issue by dappledaily** [depub-team/depub.space#84]
With an extra /post

e.g.:
https://depub.space/post/wrnKsayRqWxqDMCSWu8SNIXyu_8bSgubaRWYkbiP6ho/1

should be:
https://depub.space/wrnKsayRqWxqDMCSWu8SNIXyu_8bSgubaRWYkbiP6ho/1

**Comment by 0xtaipoian** [comment]
Fixed
