### ISSUE TITLE
Logo resources

### ISSUE THREAD

**Issue by hkyoma** [depub-team/depub.space#9]
![depub_logo_final](https://user-images.githubusercontent.com/98076197/150902758-09add445-9dcd-44ce-bb8f-db7f722cdcba.svg)
![depub_logo_512](https://user-images.githubusercontent.com/98076197/150902762-0d6acbac-c038-4821-a45e-71bb9901ff6a.png)

![depub_logo_1024](https://user-images.githubusercontent.com/98076197/150902767-fca37acb-3bbf-42da-ab14-fbeba7d0511d.png)

**Comment by 0xtaipoian** [comment]
Thanks for share, will update a bit.

**Comment by 0xtaipoian** [comment]
v2 ![depub space](https://user-images.githubusercontent.com/81803414/151076743-27c6e0c4-e5c8-4825-8086-99e273d2a212.jpg)

**Comment by 0xtaipoian** [comment]
#07D6A0 for space

**Comment by 0xtaipoian** [comment]
![logo-icon-text](https://user-images.githubusercontent.com/81803414/151077893-90ad4696-94f1-4806-9335-3902408af462.svg)
![logo-icon](https://user-images.githubusercontent.com/81803414/151077895-0a4009a5-a5b6-4991-a016-127897b3ec67.svg)
![logo-text-page](https://user-images.githubusercontent.com/81803414/151077898-7c802218-52bc-4994-b7f3-931910b00c9f.svg)
![logo-text](https://user-images.githubusercontent.com/81803414/151077899-459a2d56-c0c3-448e-b93a-34a984ba6c90.svg)
![logo-icon-text-page](https://user-images.githubusercontent.com/81803414/151077892-1487d428-2cf0-49da-aba1-52fa118688ba.svg)
![logo-icon-page](https://user-images.githubusercontent.com/81803414/151077891-3ebc43ab-99cd-4954-981b-dd3638d0df36.svg)

**Comment by 0xtaipoian** [comment]
#07D6A0 for space
#9A15EA for page

![logo-icon-page](https://user-images.githubusercontent.com/81803414/151079055-157f747f-7025-4efa-95ec-a6d9dd059ebf.svg)
![logo-icon-text-page](https://user-images.githubusercontent.com/81803414/151079058-8b7f604b-173c-486e-8823-16ed5ee099c3.svg)
![logo-icon-text](https://user-images.githubusercontent.com/81803414/151079060-afc9e84f-2554-4800-80b9-ddd4abfdc00d.svg)
![logo-icon](https://user-images.githubusercontent.com/81803414/151079061-e7ce06f6-7d67-4c3d-879b-368ef84d9b00.svg)
![logo-text-page](https://user-images.githubusercontent.com/81803414/151079062-215f9f77-2fed-4929-b035-84c5a3324c7d.svg)
![logo-text](https://user-images.githubusercontent.com/81803414/151079064-23926ae6-1964-43ae-981c-edb6b57e45da.svg)

**Comment by 0xtaipoian** [comment]
![logo-icon-page](https://user-images.githubusercontent.com/81803414/151081376-4d3e046f-289c-42f7-9ec2-bcffbfeb1a38.svg)
![logo-icon-text-page](https://user-images.githubusercontent.com/81803414/151081380-774c61e4-7939-4e39-931b-6905febe1431.svg)
![logo-icon-text](https://user-images.githubusercontent.com/81803414/151081382-426a165a-ac1a-41e5-b320-d7d2c21e8487.svg)
![logo-icon](https://user-images.githubusercontent.com/81803414/151081384-c3b23a14-c999-4e83-83d7-182676176b8d.svg)
![logo-text-page](https://user-images.githubusercontent.com/81803414/151081386-ddb72fc4-1b19-4fe7-9c78-dbd3b1da5435.svg)
![logo-text](https://user-images.githubusercontent.com/81803414/151081387-d87f850c-0ce4-4b86-add9-c520447575da.svg)

**Comment by 0xtaipoian** [comment]
![h-logo-text](https://user-images.githubusercontent.com/81803414/155306381-ab564522-fae5-4baa-bec0-759ecbb165be.svg)
